apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python
spec:
  selector:
    matchLabels:
      app: simple-python
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-python
    spec:
      containers:
      - name: simple-python
        image: cerpin/simple-python-app:latest
        ports:
        - containerPort: 5002