apiVersion: v1
kind: Service
metadata:
  labels:
  k8s-app: simple-python-app
  name: simple-python-app
  namespace: simple-python-app
spec:
  type: NodePort
  ports:
  - port: 5002
  selector:
  k8s-app: simple-python-app