name: CI

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Silame83/simple-python-app@master
      
      - name: Docker Build & Push to Docker Hub
        uses: Silame83/simple-python-app@master
        env:
          USERNAME: Silame83
          PASSWORD: Orthio99
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "silame83/spa"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
