name: CI

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build & Push to Docker Hub
        uses: Silame83/simple-python-app@master
        env:
          USERNAME: ${{ secrets.Silame83 }}
          PASSWORD: ${{ secrets.Orthio99 }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "USERNAME/IMAGE_NAME"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
